import { Address, Cart, Order, Product } from "@/types";

// Données fictives pour les espaces réservables
export const mockProducts: Product[] = [
  {
    _id: "1",
    name: "Olona Talents",
    description: "Un espace de coworking moderne avec des talents, idéal pour faire grandir votre entreprise. Équipé de bureaux, salles de réunion et espaces collaboratifs.",
    price: 450,
    stock: 50,
    category: "Coworking Space",
    images: ["https://olona-talents.com/images/logo-og.png", "https://olona-talents.com/images/pubs/olona-talents-vertical.webp"],
    averageRating: 4.8,
    totalReviews: 234,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    _id: "2",
    name: "Tech Hub Coworking",
    description: "Espace de coworking high-tech avec connexion fibre, imprimantes 3D et zones de détente. Parfait pour les startups et freelances.",
    price: 180,
    stock: 40,
    category: "Coworking Space",
    images: ["https://via.placeholder.com/400x400?text=Coworking+Space"],
    averageRating: 4.7,
    totalReviews: 189,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
  },
  {
    _id: "3",
    name: "Grand Event Hall",
    description: "Salle de réception spacieuse pouvant accueillir jusqu'à 500 personnes. Idéale pour mariages, conférences et événements corporatifs.",
    price: 2500,
    stock: 10,
    category: "Event Hall",
    images: ["https://via.placeholder.com/400x400?text=Event+Hall"],
    averageRating: 4.9,
    totalReviews: 156,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
  },
  {
    _id: "4",
    name: "Elegant Ballroom",
    description: "Salle de bal élégante avec parquet, éclairage professionnel et système son. Capacité 300 personnes, parfait pour soirées et galas.",
    price: 2200,
    stock: 8,
    category: "Event Hall",
    images: ["https://via.placeholder.com/400x400?text=Ballroom"],
    averageRating: 4.6,
    totalReviews: 98,
    createdAt: "2024-01-18T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
  },
  {
    _id: "5",
    name: "Cozy Downtown Apartment",
    description: "Appartement moderne et confortable en centre-ville. 2 chambres, cuisine équipée, wifi haut débit. Idéal pour séjours courts ou longs.",
    price: 350,
    stock: 15,
    category: "Airbnb",
    images: ["https://via.placeholder.com/400x400?text=Apartment"],
    averageRating: 4.8,
    totalReviews: 312,
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-12T10:00:00Z",
  },
  {
    _id: "6",
    name: "Luxury Penthouse",
    description: "Penthouse de luxe avec vue panoramique, terrasse privée et équipements haut de gamme. 3 chambres, jacuzzi, service concierge.",
    price: 1200,
    stock: 5,
    category: "Airbnb",
    images: ["https://via.placeholder.com/400x400?text=Penthouse"],
    averageRating: 4.9,
    totalReviews: 87,
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-14T10:00:00Z",
  },
  {
    _id: "7",
    name: "Executive Suite Hotel",
    description: "Suite exécutive dans un hôtel 4 étoiles. Chambre spacieuse, salle de bain privée, minibar, service room service 24/7.",
    price: 450,
    stock: 20,
    category: "Hotel Room",
    images: ["https://via.placeholder.com/400x400?text=Hotel+Suite"],
    averageRating: 4.5,
    totalReviews: 423,
    createdAt: "2024-01-16T10:00:00Z",
    updatedAt: "2024-01-16T10:00:00Z",
  },
  {
    _id: "8",
    name: "Deluxe Double Room",
    description: "Chambre double de luxe avec lit king-size, vue sur la ville, wifi gratuit et petit-déjeuner inclus. Hôtel 3 étoiles.",
    price: 280,
    stock: 30,
    category: "Hotel Room",
    images: ["https://via.placeholder.com/400x400?text=Hotel+Room"],
    averageRating: 4.4,
    totalReviews: 267,
    createdAt: "2024-01-17T10:00:00Z",
    updatedAt: "2024-01-17T10:00:00Z",
  },
  {
    _id: "9",
    name: "Boardroom Premium",
    description: "Salle de réunion premium avec écran 4K, système de visioconférence, tableau interactif. Capacité 20 personnes, idéale pour présentations.",
    price: 320,
    stock: 12,
    category: "Meeting Room",
    images: ["https://via.placeholder.com/400x400?text=Meeting+Room"],
    averageRating: 4.7,
    totalReviews: 145,
    createdAt: "2024-01-11T10:00:00Z",
    updatedAt: "2024-01-11T10:00:00Z",
  },
  {
    _id: "10",
    name: "Creative Meeting Space",
    description: "Espace de réunion créatif avec murs effaçables, mobilier modulaire et équipements multimédias. Parfait pour brainstorming et workshops.",
    price: 250,
    stock: 15,
    category: "Meeting Room",
    images: ["https://via.placeholder.com/400x400?text=Creative+Space"],
    averageRating: 4.6,
    totalReviews: 203,
    createdAt: "2024-01-13T10:00:00Z",
    updatedAt: "2024-01-13T10:00:00Z",
  },
  {
    _id: "11",
    name: "FabLab Innovation",
    description: "Laboratoire de fabrication numérique avec imprimantes 3D, découpeuses laser, fraiseuses CNC et outils électroniques. Accès à tous les équipements.",
    price: 200,
    stock: 8,
    category: "FabLab",
    images: ["https://via.placeholder.com/400x400?text=FabLab"],
    averageRating: 4.8,
    totalReviews: 92,
    createdAt: "2024-01-19T10:00:00Z",
    updatedAt: "2024-01-19T10:00:00Z",
  },
  {
    _id: "12",
    name: "Maker Space Workshop",
    description: "Atelier makerspace complet avec machines-outils, postes de soudure, imprimantes 3D et espace de prototypage. Formation incluse.",
    price: 180,
    stock: 10,
    category: "FabLab",
    images: ["https://via.placeholder.com/400x400?text=Maker+Space"],
    averageRating: 4.9,
    totalReviews: 67,
    createdAt: "2024-01-21T10:00:00Z",
    updatedAt: "2024-01-21T10:00:00Z",
  },
];

// Données fictives pour les adresses
export const mockAddresses: Address[] = [
  {
    _id: "addr1",
    label: "Home",
    fullName: "Jean Dupont",
    streetAddress: "123 Rue de la République",
    city: "Paris",
    state: "Île-de-France",
    zipCode: "75001",
    phoneNumber: "+33123456789",
    isDefault: true,
  },
  {
    _id: "addr2",
    label: "Work",
    fullName: "Jean Dupont",
    streetAddress: "456 Avenue des Champs-Élysées",
    city: "Paris",
    state: "Île-de-France",
    zipCode: "75008",
    phoneNumber: "+33123456789",
    isDefault: false,
  },
];

// Données fictives pour les commandes (réservations)
export const mockOrders: Order[] = [
  {
    _id: "order1",
    user: "user1",
    clerkId: "clerk_user1",
    orderItems: [
      {
        _id: "item1",
        product: mockProducts[0],
        name: mockProducts[0].name,
        price: mockProducts[0].price,
        quantity: 1,
        image: mockProducts[0].images[0],
      },
    ],
    shippingAddress: {
      fullName: "Jean Dupont",
      streetAddress: "123 Rue de la République",
      city: "Paris",
      state: "Île-de-France",
      zipCode: "75001",
      phoneNumber: "+33123456789",
    },
    paymentResult: {
      id: "pay_123",
      status: "succeeded",
    },
    totalPrice: 25,
    status: "delivered",
    hasReviewed: false,
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
  },
  {
    _id: "order2",
    user: "user1",
    clerkId: "clerk_user1",
    orderItems: [
      {
        _id: "item2",
        product: mockProducts[2],
        name: mockProducts[2].name,
        price: mockProducts[2].price,
        quantity: 1,
        image: mockProducts[2].images[0],
      },
      {
        _id: "item3",
        product: mockProducts[8],
        name: mockProducts[8].name,
        price: mockProducts[8].price,
        quantity: 1,
        image: mockProducts[8].images[0],
      },
    ],
    shippingAddress: {
      fullName: "Jean Dupont",
      streetAddress: "456 Avenue des Champs-Élysées",
      city: "Paris",
      state: "Île-de-France",
      zipCode: "75008",
      phoneNumber: "+33123456789",
    },
    paymentResult: {
      id: "pay_456",
      status: "succeeded",
    },
    totalPrice: 575,
    status: "shipped",
    hasReviewed: false,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
  },
];

// État initial du panier (vide)
export const getInitialCart = (): Cart => ({
  _id: "cart1",
  user: "user1",
  clerkId: "clerk_user1",
  items: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

